import Link from 'next/link'

export const metadata = {
  title: 'Terms of Service — Converge',
}

export default function TermsPage() {
  return (
    <div className="min-h-full bg-background">
      <header className="border-b border-border/30 bg-background/80 px-6 py-3 backdrop-blur-md">
        <Link href="/">
          <img src="/brand/lockup-option2-horizontal.svg" alt="Converge" className="h-7" />
        </Link>
      </header>

      <main className="mx-auto max-w-[640px] px-6 py-12">
        <h1 className="mb-2 text-2xl font-semibold tracking-tight">Terms of Service</h1>
        <p className="mb-10 text-sm text-muted-foreground">Last updated: June 30, 2026</p>

        <div className="space-y-8 text-sm leading-relaxed text-foreground/90">
          <section>
            <h2 className="mb-2 text-base font-semibold">Agreement</h2>
            <p>By using Converge, you agree to these terms. If you don&apos;t agree, don&apos;t use the service.</p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold">What Converge provides</h2>
            <p>Converge is an AI-powered knowledge search tool that connects to your work tools (Google Drive, Gmail, Slack, Jira) and lets you search across them with natural-language queries. Answers are AI-generated and may not always be accurate — always verify critical information against the cited sources.</p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold">Your account</h2>
            <ul className="list-disc space-y-1.5 pl-5">
              <li>You sign in via Google OAuth. You&apos;re responsible for your account security.</li>
              <li>You must have authorization to connect any tool you link to Converge.</li>
              <li>Don&apos;t use Converge to process data you don&apos;t have rights to access.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold">Your data</h2>
            <p>You retain ownership of all data you connect to Converge. We process it solely to provide the search service. See our <Link href="/privacy" className="text-primary underline underline-offset-2">Privacy Policy</Link> for details on data handling, retention, and deletion.</p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold">Acceptable use</h2>
            <ul className="list-disc space-y-1.5 pl-5">
              <li>Don&apos;t attempt to access other users&apos; data.</li>
              <li>Don&apos;t reverse-engineer, overload, or abuse the service.</li>
              <li>Don&apos;t use Converge for any unlawful purpose.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold">AI-generated content</h2>
            <p>Answers are generated by AI models and may contain errors. Converge provides source citations so you can verify claims. We are not liable for decisions made based on AI-generated answers.</p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold">Service availability</h2>
            <p>Converge is provided &ldquo;as is.&rdquo; We don&apos;t guarantee uninterrupted availability. We may modify or discontinue features at any time.</p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold">Termination</h2>
            <p>You can stop using Converge at any time by disconnecting your tools and requesting account deletion. We may suspend accounts that violate these terms.</p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold">Contact</h2>
            <p>Questions about these terms? Contact us at <a href="mailto:mohit.goyal.contact@gmail.com" className="text-primary underline underline-offset-2">mohit.goyal.contact@gmail.com</a>.</p>
          </section>
        </div>

        <div className="mt-12 border-t border-border/30 pt-6 text-xs text-muted-foreground">
          <Link href="/privacy" className="underline underline-offset-2 hover:text-foreground">Privacy Policy</Link>
          <span className="mx-2">·</span>
          <Link href="/" className="underline underline-offset-2 hover:text-foreground">Back to Converge</Link>
        </div>
      </main>
    </div>
  )
}
